server:
  port: ENC(y7L0BSydHapTOK3QO+guMg==)

spring:
  profiles:
    include: db, jasypt, notification, cloud

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

# logger
#logging.level:
#  org.hibernate.SQL: info
#  org.hibernate.type: trace
