spring:
  # MariaDB
  datasource:
    url: ENC(tq3IL4VLVsnulAL6J785QYgbOSyMRA0VEyJYtkr3pLaaJ7bUA4Cu14a9P6iwWBUifwdFN8PID3J7LaoMMYGHhw==)
    username: ENC(ySBkqn7rc0rzhCnJx1aNtMcQdtGI7IRQ)
    password: ENC(i7j46L3hTWPdOmMe3uGWug==)
    driver-class-name: org.mariadb.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false