spring:
  # MariaDB
  datasource:
    url: ENC(5aU26rvopds6JmpQlwnKoLS+5i847duy8xfoFWMoVFd0eauwtobRrpSI/br9ER9E) #    url: jdbc:mysql://localhost:3306/cobby_user
    username: ENC(IPgCgyTJy4ppIk29iI4ZtQ==)
    password: ENC(RxvZ2uV26b8mNcoGdRj5JQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true