spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(nAlgFbHkFPhfBthdidNy20y29nmDOZyuMIu6mQLN2RA=)
            client-secret: ENC(kjWNF+oXrnlxbiwzy7OE8LQzm+YxumkGMVxUVF+RE6OjZiia5Je3paMCP5sW0b8C5C4gQrMhaCo=)
            redirect-uri: ENC(eUYQwg8ALIuHZYR4gh8qqZUln7OKpg1J2lqEMZ8i2qhP9Gmj44WxqNW3fiDveIRFujE92Zq0mtQ=)
#            scope: id, login, html_url
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github

jwt:
  header: Authorization
  secret: Token-Secret-Key-Test-Token-Secret-Key-Test-Token-Secret-Key-Test
  token-validity-in-seconds: 3600
#  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
#  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)
