spring:
  data:
    mongodb:
      host: ENC(e6Uv5RpXd/fm/4vz63QuFU+f7RsbBc4vH9JdYF0FVRs=)
      port: ENC(V95UBnfXEUarkvxGYRliCg==)
      database: ENC(X3Db90LZ/lGUb8kI5nyQxBABbCjWceaR)
      username: ENC(ySBkqn7rc0rzhCnJx1aNtMcQdtGI7IRQ)
      password: ENC(i7j46L3hTWPdOmMe3uGWug==)
      uuid-representation: standard
  # JPA Properties
  jpa:
    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true

redis:
  host: k8b201.p.ssafy.io
  port: 6379

request:
  url:
#    user-server: ENC(1pDCxkeJgc4aLRGg5QSemS7fx6MPMuOaJ589WQ1UwWeq6PIuLFCf087yvuEA1ZJr)
    user-server: ${COBBY_AUTH_USER_SERVER}
    front-login: https://cobby-play.com