spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(UKILsruzlzfL6gbhzRrubRRTwmtRDAwafcdwRujPbSQ=)
            client-secret: ENC(u+FTtmWZ7F4dzOUcDzNA2mFotczeq2FnbLw2+wfG23C8Ne6RWUiP8E9qp4FAhybG68wD+O0jSyU=)
            redirect-uri: ENC(94K13AJo5J8b/SnX1Ay/+2BtN+aZfk1CDFqkD57A1zS2wT159eInBeLXcfr565HXUGkRL5Bwhsg=)

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)