spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(Gu4NQdtxEiMKfAsRG24Rmc/Kplm9793uWMckKLlcczI=)
            client-secret: ENC(VnPuZw5A/aMmhHCnOhNnYU5wf1hTp1/luKkYKndInFAUp1vpJjM/vvJoo+WmmHychdzdsoZQuXw=)
            redirect-uri: https://cobby-play.com/login/oauth2/code/github
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github
#            redirect-uri: ENC(B/gqg5gwRZJJMpFR1BmsB4FedREvx/gUwdGZiMNZHm3mMv4FZM9WXe4+2kThS9FVoqneXvwiwAc=)

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)