spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b8ef7b59157b67a1
            client-secret: 2895aaaa570f5b5eb41559c10f06d91d8aefc4d5
            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github
#            redirect-uri: https://cobby-play.com/login/oauth2/code/github

jwt:
  header: Authorization
  secret: test
  token-validity-in-seconds: 3600