spring:
  data:
    mongodb:
      uri: ENC(DebMT298nVSlzfI01wpkrrtyYv8X94bkMzwAGjrGsL7xilgEgx0xaZljvzfZnxR+yG4Mco4tank=)
      uuid-representation: standard
      username: ENC(ySBkqn7rc0rzhCnJx1aNtMcQdtGI7IRQ)
      password: ENC(i7j46L3hTWPdOmMe3uGWug==)
  # JPA Properties
  jpa:
    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true

request:
  url:
    user-server: http://k8b201.p.ssafy.io:15010/api/users
    front-login: https://cobby-play.com