spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b8ef7b59157b67a1
            client-secret: 6d659f4c9b980ce5b07bf24602379750adacf9e0
            redirect-uri: https://cobby-play.com/login/oauth2/code/github
#            scope: id, login, html_url
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)
