spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(9xEmPP82PcZpAtopRPkxFQNGGCrSmfED/FZVfFa4lyM=)
            client-secret: ENC(JD1KbZaMCD+ovDe85yvGM8dV5gB5irrxJvyaw6cHdrT9+9Ik029sqapwuR/Y3LZMV7Gp9QcNSGY=)
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github
            redirect-uri: https://cobby-play.com/login/oauth2/code/github

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)