spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(cGZ2aSg57gtrME04EfID2lBDd/VHSF8AP0f1+MUNJ9k=)
            client-secret: ENC(cc1Tdktj6b8yo7BBlrVVlGvrQWRh2ou18OG7Ez9c1IZIsLaprF3XMlpi07RcSFNCcgoK8O6vkDE=)
#            redirect-uri: ENC(RTfTf+THRqR8vwtyf5UKB7N/zo27ljU5IU18ND8c8h4kYaoVtD9rsysHCX3Yyy/lBXVWFTv7pUs=)
            redirect-uri: http://localhost:15010/login/oauth2/code/github

jwt:
  header: Authorization
  secret: ENC(Oc+80dgjgizjttruyKyevjLMfdIYEG0mfHgQs2byYEM7nwCVizEPeuZ7wR7EYv5IfBkbeknXNr4=)
  token-validity-in-seconds: 3600
