spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b8ef7b59157b67a1
            client-secret: d5a9446ba64448494db426b97ff0830c82647145
            redirect-uri: https://cobby-play.com/login/oauth2/code/github
#            scope: id, login, html_url
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github

jwt:
  header: Authorization
  secret: Token-Secret-Key-Test-Token-Secret-Key-Test-Token-Secret-Key-Test
  token-validity-in-seconds: 3600
#  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
#  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)
