spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          # 요청 http://localhost:8091/oauth2/authorization/github
          github:
            client-id: Iv1.38f5e106f8354b75
            client-secret: 042d0af425cd72d603989b4124a3f618bdd69d1b
            redirect-uri: http://localhost:8091/login/oauth2/code/github

# jwt
# secret : TheCobby-With-Github-앙기모띠

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)
  # 3600