spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          # 요청 http://localhost:8090/oauth2/authorization/github
          github:
            client-id: Iv1.38f5e106f8354b75
            client-secret: 042d0af425cd72d603989b4124a3f618bdd69d1b
            redirect-uri: http://localhost:8090/login/oauth2/code/github

# jwt
# secret : TheCobby-With-Github-앙기모띠

jwt:
  header: Authorization
  secret: ENC(l1yeteErqi6d0eOX5IhLmB+kp7celucCmtdpF1Ptqg/4Cn/6byPDTVV5P4TiMXo5)
  token-validity-in-seconds: ENC(yCuYFmsIi+oUEJ35qXkmhw==)
  # 3600