spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${COBBY_AUTH_CLIENT_ID}
            client-secret: ${COBBY_AUTH_CLIENT_SECRET}
            redirect-uri: ${COBBY_AUTH_REDIRECT_URI}

jwt:
  header: Authorization
  secret: ${COBBY_AUTH_JWT_SECRET}
  token-validity-in-seconds: 3600
