spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(9xEmPP82PcZpAtopRPkxFQNGGCrSmfED/FZVfFa4lyM=)
            client-secret: 2895aaaa570f5b5eb41559c10f06d91d8aefc4d5
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github
            redirect-uri: https://cobby-play.com/login/oauth2/code/github

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)