spring:
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${COBBY_AUTH_CLIENT_ID}
            client-secret: ${COBBY_AUTH_CLIENT_SECRET}
            redirect-uri: ${COBBY_AUTH_REDIRECT_URI}
#            scope: id, login, html_url
#            redirect-uri: https://k8b201.p.ssafy.io/login/oauth2/code/github

jwt:
  header: Authorization
  secret: ENC(NYP5wOkr9mRy0MU0wLCCH3RyUzXPW7y8kdV6ulRnAl5tqFmibQvOwfgP4F4ddRIW)
  token-validity-in-seconds: ENC(LGbwoiwuT+A+flqW0uw1Aw==)
