spring:
  # mongodb setting
  data:
    mongodb:
      uri: ENC(es+S/14D3HgJAfa3+Cjvz6BcF+2VBm6IrHjhiCuLJDxzkgg27kSsP5ZDtcg+yXqXCPRrzsDDcTE=)
      uuid_representation: standard
      username: ENC(ySBkqn7rc0rzhCnJx1aNtMcQdtGI7IRQ)
      password: ENC(i7j46L3hTWPdOmMe3uGWug==)

  # mongodb database auto create
  jpa:
    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true