spring:
  # MysqlDB
  datasource:
    url: ENC(PaoYUCo2AMIchkpEizHVZyVIVYMs6dsvmBatVrWQY8YnJAQfIjK0JbSCVcUBQW7GUgYih2brEpe3yDtst0NvSw==)
    username: ENC(ySBkqn7rc0rzhCnJx1aNtMcQdtGI7IRQ)
    password: ENC(i7j46L3hTWPdOmMe3uGWug==)
    driver-class-name: org.mariadb.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
